name: Defuncto.Assertions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/DeFuncto.sln
    - name: Build
      run: dotnet build -c Release --no-restore ./src/DeFuncto.Assertions/DeFuncto.Assertions.csproj
    - name: Test
      working-directory: ./src
      run: dotnet test
    - name: Package
      run: dotnet pack -c Release -o . ./src/DeFuncto.Assertions/DeFuncto.Assertions.csproj
    - name: Publish
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
